# Site settings
title: Mehmet ARI
description: 'Mehmet ARI - Junior Software Engineer'
url: 'http://arimehmet.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mehmet ARI'
  email: memojja1907@gmail.com
  twitter_username: memojja
  facebook_username: memojja
  github_username:  memojja
  linkedin_username:  arimehmet

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
 - jekyll-paginate
 - jemoji
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

